const mirrorHexColors = colors => Object.fromEntries(
  colors.map((color, index) => {
    if(!/#[a-f0-9]{6}/.test(color)) {
      throw new Error(
        'All colors should be lowercase hexadecimal strings 7 characters long with "#" sign at the beginning',
      )
    }

    if(colors.indexOf(color) !== index) {
      throw new Error('Colors should be unique')
    }

    if(colors[index-1] > color) {
      throw new Error('Colors should be sorted alphabetically')
    }

    return [color.substring(1), color]
  }),
)

module.exports = {
  content: [
    './src/**/*.tsx',
  ],

  theme: {
    extend: {
      colors: {
        ...mirrorHexColors([
          '#000000',
          '#08955a',
          '#105f48',
          '#1d102f',
          '#1e1e23',
          '#20b078',
          '#21725a',
          '#61577c',
          '#6448e7',
          '#977cc0',
          '#b954f5',
          '#c2a4e5',
          '#ca74fe',
          '#df57bc',
          '#f4b4b6',
          '#f66651',
          '#ffffff',
        ])
      },

      fontFamily: {
        main : ['Inter', 'san-serif'],
        mono : ['DM Sans', 'sans-serif'],
        serif: ['Berlingske', 'serif'],
      },
    }
  },

  "//":"~~ Generated by projen. To modify, edit .projenrc.js and run \"npx projen\"."
}
